"""added userlog (real)

Revision ID: b8d9da3c4a67
Revises: 94ce1b6e256e
Create Date: 2026-01-09 21:27:54.193918

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8d9da3c4a67'
down_revision: Union[str, Sequence[str], None] = '94ce1b6e256e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tg_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('today_water', sa.Float(), nullable=False),
    sa.Column('today_calories', sa.Float(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['tg_id'], ['users.tg_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_log_tg_id'), 'user_log', ['tg_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_log_tg_id'), table_name='user_log')
    op.drop_table('user_log')
    # ### end Alembic commands ###
