"""initial schema

Revision ID: f69587fcdc34
Revises: 
Create Date: 2026-01-08 18:12:36.233208

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f69587fcdc34'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tg_id', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('height', sa.Float(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('activity', sa.Integer(), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('water_goal', sa.Float(), nullable=True),
    sa.Column('calorie_goal', sa.Float(), nullable=True),
    sa.Column('logged_water', sa.Float(), nullable=True),
    sa.Column('added_water', sa.Float(), nullable=True),
    sa.Column('logged_calories', sa.Float(), nullable=True),
    sa.Column('burned_calories', sa.Float(), nullable=True),
    sa.Column('cur_date', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tg_id')
    )
    op.create_table('user_history',
    sa.Column('tg_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('water_goal', sa.Float(), nullable=True),
    sa.Column('calorie_goal', sa.Float(), nullable=True),
    sa.Column('logged_water', sa.Float(), nullable=False),
    sa.Column('logged_calories', sa.Float(), nullable=False),
    sa.Column('burned_calories', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['tg_id'], ['users.tg_id'], ),
    sa.PrimaryKeyConstraint('tg_id', 'date')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_history')
    op.drop_table('users')
    # ### end Alembic commands ###
